### PR TITLE
Fixed 'Undefined offset: -1' notice.

### PR DESCRIPTION
**Pull request by marceltoben**
This small change avoids a php notice.

### CODE REVIEW

**Comment by danez** [comment]
I added a test used`array_key_exists()` instead of `isset`. 

Lots of other tests seem to fail.

**Comment by derickr** [comment]
Happy to merge this - but can you please split the commit in two - one for the real fix, and one for the white space changes?

**Comment by danez** [comment]
I removed the whitespace change.

**Comment by derickr** [comment]
Merged (After rebase, and a change). Thanks for helping out @danez and @marceltoben !

**Pull request closed without merging**
