### PR TITLE
PHP 8.1/8.2 and PHPUnit 8.0 compatibility fixes

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by sapphirecat** [comment]
I couldn't see the CI logs, but running the test in my own environment (linux x86-64, Ubuntu 20.04, [Ondřej Surý's PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php)), PHP 8.1.2 mbstring seems to be removing all bytes >=128 from the outputs.

```
1) ezcMailParserTest::testMbstringCharsetConverter1
Failed asserting that 459 matches expected 468.

/home/ubuntu/Mail/tests/parser/parser_test.php:1447

2) ezcMailParserTest::testMbstringCharsetConverter2
Failed asserting that 98 matches expected 99.

/home/ubuntu/Mail/tests/parser/parser_test.php:1466
```

The first test data has 3x `EF BF BD` (U+FFFD replacement character, UTF-8 encoded) sequences with no charset defined, and the second has an `=F6` quoted-printable byte with us-ascii charset selected.  The difference between actual and expected numbers suggest these octets are being deleted.

I wanted to propose a solution, but I'm not sure what to do.  I haven't found any evidence that this was an intentional change of behavior in PHP 8.1, nor how to select previous behavior.

**Comment by derickr** [comment]
@sapphirecat Sorry that I'm only just getting to this, I hadn't realised there was a new comment here.

**Comment by seamuslee001** [comment]
@derickr @sapphirecat I am wondering if it is this https://kinsta.com/blog/php-8-1/#explicit-octal-numeral-notation  that seems to be only thing I have found relating to Octets

**Comment by sapphirecat** [comment]
I just want to say, I won't be of much help with this going forward. We switched over to `nette/mail` a few months back.

**Pull request merged**
